import {
    add,
    arrowDown,
    arrowLeft,
    close,
    search,
    interrogation,
    positionBot,
    positionJungle,
    positionMid,
    positionSupport,
    positionTop,
    bookmark,
    edit,
    notificationAll,
    notificationNone,
    settings,
    star,
    calendar,
    camera,
    filter,
    share
} from './iconsText';

export const iconsPaths: Record<string, string> = {
    add,
    'arrow-down': arrowDown,
    close,
    search,
    interrogation,
    'position-bot': positionBot,
    'position-jungle': positionJungle,
    'position-mid': positionMid,
    'position-support': positionSupport,
    'position-top': positionTop,
    'arrow-left': arrowLeft,
    bookmark,
    edit,
    'notification-all': notificationAll,
    'notification-none': notificationNone,
    settings,
    star,
    calendar,
    camera,
    filter,
    share
}